.TH "guicavane" "1"
.SH NAME
guicavane \- a graphical user interface for the cuevana.tv website.
.SH SYNOPSIS
.B guicavane
.SH DESCRIPTION
\fBGuicavane\fP tries to bring to the desktop the functionality provided by
the website \fIwww.cuevana.tv\fP. That is the posibility to watch series
and movies streaming from a free online storage server such as
\fImegaupload\fP.
.PP
\fBGuicavane\fP uses \fIGTK toolkit\fP for the frontend with \fIGlade\fP as ui design.
For the backend uses a library made by \fIRoger Duran\fP, \fIpycavane\fP.
is a program that...
.SH OPTIONS
\fBguicavane\fP takes no command line options
.SH SEE ALSO
.BR GNOME (1),
.br
.SH AUTHOR
guicavane was written by j0hn <j0hn.com.ar@gmail.com> and Julia
Medina <who.knows.shia@gmail.com>.
.PP
This manual page was written by Niv Sardi <xaiki@debian.org>,
for the Debian project (and may be used by others).
